### ISSUE TITLE
Initial authentication - Invalid redirect URI

### ISSUE THREAD

**Issue by digitallymarked** [EwanLyon/ncg-spotify#1]
Can't authenticate with Spotify. Receive **INVALID_CLIENT: Invalid redirect URI**

Steps to fix:

1. Go to Spotify App Dashboard and click Edit Settings
2. Add `http://localhost:9090/bundles/ncg-spotify/spotify-callback/index.html` as a Redirect URI
3. Save and retry

**Comment by EwanLyon** [comment]
Thank you for pointing this out, seems I forgot about it when writing the installation. Fixed in c7007a15fb6b49cddfc66c9bdbed7af62b8de076
