### ISSUE TITLE
Playing value not updating

### ISSUE THREAD

**Issue by digitallymarked** [EwanLyon/ncg-spotify#2]
When Pausing/Playing, the value in the replicant isn't updating.

Issue: 
https://github.com/EwanLyon/ncg-spotify/blob/c7007a15fb6b49cddfc66c9bdbed7af62b8de076/dist/extension/spotify.js#L71 is missing `&& currentSongRep.value.playing == data.body.is_playing` from https://github.com/EwanLyon/ncg-spotify/blob/c7007a15fb6b49cddfc66c9bdbed7af62b8de076/src/extension/spotify.ts#L99

Fix:
Running `npm run-script build` / `npm run-script build:extension` fixes issue for me

**Comment by EwanLyon** [comment]
Should all be fixed in 7af47b7663935f18be7a4d31e880c7862d9facba
