### ISSUE TITLE
`data.body.item` may be `undefined` on first time start causing crash

### ISSUE THREAD

**Issue by jai-x** [EwanLyon/ncg-spotify#8]
This line causes a crash on a first time start with `data.body['item']` returning `undefined`.

https://github.com/EwanLyon/ncg-spotify/blob/a47c190051ac489b695213b6463199609df4e14d/src/extension/index.ts#L118

I've ended up making a fork to quickly fix this for me, but I thought you should know too:

https://github.com/jai-x/nodecg-spotify

**Comment by EwanLyon** [comment]
Thank you for pointing that out. Its been a while since I looked at this but I'll probably refactor a bit since I have more experience.

**Comment by EwanLyon** [comment]
Fixed in e673d512fb373075cda203814a029c3685b7444b
